import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./storeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const bodyStyle = `container h-screen m-auto`;

  return (
    <html lang="ko">
      <StoreProvider>
        <body className={inter.className + " " + bodyStyle}>{children}</body>
      </StoreProvider>
    </html>
  );
}
